# Generated by Django 4.2.5 on 2024-04-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinec_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healName', models.CharField(help_text='اسم الاصابه', max_length=50)),
                ('injuryImg', models.ImageField(blank=True, null=True, upload_to='Clenic site/Clenic/', verbose_name='Injury photo')),
                ('healinfo', models.TextField(help_text='معلومات عنها و طريقه الوقايه منها و طرق علاجها')),
                ('details', models.TextField(default='', help_text='تفاصيل عن طرق علاجها بالمركز')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='رأس الموضوع', max_length=500)),
                ('body', models.TextField(help_text='الموضوع', max_length=500000)),
            ],
        ),
    ]
