# Generated by Django 5.0.1 on 2024-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinec_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healName', models.CharField(help_text='اسم الاصابه', max_length=50)),
                ('healinfo', models.CharField(help_text='معلومات عنها و طريقه الوقايه منها و طرق علاجها', max_length=100000)),
            ],
        ),
    ]
