<<<<<<< HEAD
# Generated by Django 4.2.5 on 2024-02-24 23:43
=======
# Generated by Django 4.2.5 on 2024-02-25 10:40
>>>>>>> 72047f5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinec_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healName', models.CharField(help_text='اسم الاصابه', max_length=50)),
                ('injuryImg', models.ImageField(blank=True, null=True, upload_to='Clenic site/Clenic/', verbose_name='Injury photo')),
                ('healinfo', models.CharField(help_text='معلومات عنها و طريقه الوقايه منها و طرق علاجها', max_length=100000)),
                ('details', models.CharField(default='', help_text='تفاصيل عن طرق علاجها بالمركز', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='رأس الموضوع', max_length=500)),
                ('body', models.CharField(help_text='الموضوع', max_length=500000)),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
=======
>>>>>>> 72047f5
            ],
        ),
    ]
