# Generated by Django 4.2.5 on 2024-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='add_user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
