# Generated by Django 5.0.1 on 2024-02-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='رأس الموضوع', max_length=500)),
                ('body', models.CharField(help_text='الموضوع', max_length=500000)),
            ],
        ),
    ]
