# Generated by Django 4.2.5 on 2024-02-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Addusers',
        ),
    ]
