# Generated by Django 4.2.5 on 2024-02-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0002_rename_users_addusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addusers',
        ),
    ]
