# Generated by Django 5.1.3 on 2025-03-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_about_us',
            name='body',
            field=models.TextField(help_text='الموضوع'),
        ),
        migrations.CreateModel(
            name='Injury_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Injury_Photos/', verbose_name='Injury photo')),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_photos', to='Clenicapp.clinec_site')),
            ],
        ),
    ]
