# Generated by Django 5.0.1 on 2024-02-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0003_properties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
