# Generated by Django 5.1.3 on 2025-04-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clenicapp', '0004_alter_contact_name_alter_contact_phonenum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
